# Generated by Django 5.0.7 on 2024-08-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Nova notificação', max_length=255),
        ),
    ]
